### ISSUE TITLE
Refactoring SLSim - Create Catalog class to ingest catalogs or simulation pipeline outputs.

### ISSUE THREAD

**Issue by jacob-hjortlund** [LSST-strong-lensing/slsim#226]
## Current Status

`DeflectorBase` and `SourcePopBase` currently ingest the outputs of `SkyPyPipeline` instance, the SCOTCH catalog, `quasar.class.quasar_sample` etc., which all require separate subclasses. Additionally these either a collection of galaxies *or* point sources, not covering the case where we want associations between the two, see #220.  Part of the overall `SLSim` refactor, see #223. 

## Proposed Solution

Create a `Catalog` class that can be ingested by `Population`. The responsibility of the `Catalog` class is to adapt the output of a simulation pipeline, i.e `SkyPyPipeline`, or catalog to the format expected by `SLSim` and provide it for sampling by the `Population` class. It should be able to accept either a catalog of galaxies or point sources or both.

## To-Do List

- [ ] Create base class.
- [ ] Create `SkyPyCatalog` subclass for `SkyPyPipeline` ingestion and adaptation.
- [ ] Create `SCOTCHCatalog` subclass for ingestion and adaptation of SCOTCH galaxy and transient catalogs.
- [ ] Add unit tests.
