### ISSUE TITLE
Refactoring SLSim - Create Galaxy class

### ISSUE THREAD

**Issue by jacob-hjortlund** [LSST-strong-lensing/slsim#227]
## Current Status

Currently the representation of a lens or source galaxy and a potential corresponding transient is spread across multiple different classes, including `SourceBase`, `Lens`, and `Deflector`.

## Proposed Solution

Collect the responsibility of representing a galaxy and any related transient, including any necessary instantiation of composites, into a single `Galaxy` class. Instances of this class will be created by the `Population` class when samples are drawn from a `Catalog`, see #225 and #226 respectively. Additionally takes a callable `mass_model` and `light_model` to be instantiated from the provided galaxy parameters, see INSERT ISSUE HERE. This is part of the overall `SLSim` refactor, see #223.

## To-Do List

- [ ] Create `Galaxy` skeleton code.
- [ ] Add ingestion of galaxy parameters.
- [ ] Add ingestion of mass and light profiles.
- [ ] Add ingestion / handling of provided / missing transient meta data.
- [ ] Add method for providing galaxy / transient position.
- [ ] Add method for providing galaxy / transient magnitude.
- [ ] Add method for providing galaxy mass profile.
- [ ] Add method for providing galaxy light profile.
- [ ] Add unit tests.
